### ISSUE TITLE
RFC\AutumnQuicHe.github.io\layouts\partials\sidebar.html 有一个错误，应该是没推送。

### ISSUE THREAD

**Issue by 1221long** [AutumnQuicHe/AutumnQuicHe.github.io#4]
![image](https://github.com/AutumnQuicHe/AutumnQuicHe.github.io/assets/3839806/e729c07f-30dd-4fb8-8690-912d0fae68cc)
如图。

**Comment by YunzheZJU** [comment]
能否解释一下您发现的问题、问题产生的影响和您的建议？

**Comment by 1221long** [comment]
查看项目源文件，因没推送使用的还是 menu.html，但项目里面已经没有这个文件了。所以，微调一下，推送更新即可。
问题，找不到文件 hugo server 会提示错误。
